"""Initial migration

Revision ID: 5ab6b3f2efa1
Revises: 
Create Date: 2026-07-20 17:12:01.953227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab6b3f2efa1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('target_role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_logs_id'), 'scan_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_logs_ip_address'), 'scan_logs', ['ip_address'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seksi', sa.String(length=255), nullable=True),
    sa.Column('topology_x', sa.Float(), nullable=True),
    sa.Column('topology_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=False)
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=True)
    op.create_table('device_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_history_id'), 'device_history', ['id'], unique=False)
    op.create_table('device_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('cpu_brand', sa.String(length=100), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('ram_total', sa.String(length=50), nullable=True),
    sa.Column('ram_type', sa.String(length=50), nullable=True),
    sa.Column('ram_brand', sa.String(length=100), nullable=True),
    sa.Column('storage_capacity', sa.String(length=50), nullable=True),
    sa.Column('storage_type', sa.String(length=50), nullable=True),
    sa.Column('storage_brand', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_specs_id'), 'device_specs', ['id'], unique=False)
    op.create_table('ip_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seksi', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('reserved_for', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_pool_id'), 'ip_pool', ['id'], unique=False)
    op.create_index(op.f('ix_ip_pool_ip_address'), 'ip_pool', ['ip_address'], unique=True)
    op.create_table('topology_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_device_id', sa.Integer(), nullable=True),
    sa.Column('to_device_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_edges_id'), 'topology_edges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topology_edges_id'), table_name='topology_edges')
    op.drop_table('topology_edges')
    op.drop_index(op.f('ix_ip_pool_ip_address'), table_name='ip_pool')
    op.drop_index(op.f('ix_ip_pool_id'), table_name='ip_pool')
    op.drop_table('ip_pool')
    op.drop_index(op.f('ix_device_specs_id'), table_name='device_specs')
    op.drop_table('device_specs')
    op.drop_index(op.f('ix_device_history_id'), table_name='device_history')
    op.drop_table('device_history')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_scan_logs_ip_address'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_id'), table_name='scan_logs')
    op.drop_table('scan_logs')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
