"""add_seksi_to_device_history

Revision ID: 6bb0b3f2efa2
Revises: 404aa4d9875d
Create Date: 2026-07-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb0b3f2efa2'
down_revision = '404aa4d9875d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_history', sa.Column('seksi', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_history', 'seksi')
    # ### end Alembic commands ###
