"""Add brand, model, and snmp_community to Device

Revision ID: 9903182a7010
Revises: 6bb0b3f2efa2
Create Date: 2026-07-28 15:19:33.396679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9903182a7010'
down_revision: Union[str, Sequence[str], None] = '6bb0b3f2efa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('model', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('snmp_community', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'snmp_community')
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'brand')
    # ### end Alembic commands ###
